Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FPTBook.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public virtual void AddItem(Book book, int quantity)
        {
            CartLine? line = Lines
                .Where(p => p.Book.BookID == book.BookID)
                .FirstOrDefault();

            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Book = book,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Book book) =>
            Lines.RemoveAll(l => l.Book.BookID == book.BookID);

        public decimal ComputeTotalValue() =>
            Lines.Sum(e => e.Book.Price * e.Quantity);

        public virtual void Clear() => Lines.Clear();
    }

    public class CartLine
    {
        public int CartLineID { get; set; }
        public Book Book { get; set; } = new();
        public int Quantity { get; set; }
    }
}

Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FPTBook.Models;

namespace FPTBook.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FPTBook.Models;

namespace FPTBook.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { OrderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using FPTBook.Models;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using FPTBook.Models.ViewModels;

namespace FPTBook.Controllers;

public class ProductController : Controller
{
    private IStoreRepository repository;
    public int PageSize = 4;
    public ProductController(IStoreRepository repo)
    {
        repository = repo;
    }
    public ViewResult Index(int productPage = 1)
        => View(new BooksListViewModel
        {
            Books = repository.Books
                .OrderBy(p => p.BookID)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = productPage,
                ItemsPerPage = PageSize,
                TotalItems = repository.Books.Count()
            }
        });
}

Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FPTBook.Infrastructure;
using FPTBook.Models;
using Microsoft.Extensions.Logging;

namespace FPTBook.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository repository;

        public CartModel(IStoreRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string? ReturnUrl { get; set; } = "/";

        public void OnGet(string? returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long bookId, string? returnUrl)
        {
            Book? book = repository.Books
                .FirstOrDefault(p => p.BookID == bookId);
            if (book != null)
            {
                Cart.AddItem(book, 1);
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long bookId, string? returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Book.BookID == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Cart.cshtml
@page
@model CartModel
@{
    ViewData["Title"] = "Cart Page";
}

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th class="text-right">Price</th>
            <th class="text-right">Sub-total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model?.Cart?.Lines ?? Enumerable.Empty<CartLine>())
        {
            <tr>
                <td class="text-left">
                    @line.Book.Name
                </td>
                <td class="text-left">
                    @line.Quantity
                </td>
                <td class="text-left">
                    @line.Book.Price.ToString("c")
                </td>
                <td class="text-left">
                    @((line.Quantity * line.Book.Price).ToString("c"))
                </td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookID" value="@line.Book.BookID" />
                        <input type="hidden" name="ReturnUrl" value="@Model?.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right bolded">Total:</td>
            <td class="text-right bolded">@Model?.Cart?.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-danger" href="@Model?.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-danger" asp-action="Checkout" asp-controller="Order">Checkout</a>
</div>

Pages/Completed.cshtml
@page
@{
    ViewData["Title"] = "Cart Page";
    Layout = "_CartLayout";
}

<div class="text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing order #@OrderID</p>
    <p>We'll not ship your goods because this website is not real.</p>
    <a class="btn btn-danger" asp-controller="Home">Return to Store</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public string? OrderID { get; set; }
}

Pages/_CartLayout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;
@using FPTBook.Utils;

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPTBook</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" asp-append-version="true" />
</head>

<body class="p-3 mb-2 bg-white text-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 "
            style="background-color: #ffc6c6;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action=""><img src="/images/Logo.jpg"
                        style="width:110px; height: 50px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item nav-link text-dark">
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item ">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                            asp-action="">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                            asp-action="">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Product"
                                            asp-action="">All
                                            Products</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <vc:cart-summary />
            </div>
        </nav>
    </header>
    <div>
        <h1 style="color: rgb(170, 170, 255); text-align: center;">FPTBook Shop - GCS1001A - Cart Page</h1>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            <h2>Your Cart</h2>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FPTBook - GCS1001A
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>